COMMENT =	noVNC

DISTNAME =	noVNC
V =		v1.5.0
EXTRACT_SUFX =	.zip
DISTFILE =	noVNC-v1.5.0.zip
SITES =		https://github.com/novnc/noVNC/archive/refs/tags/$(V)$(EXTRACT_SUFX)

MAINTAINER =	Diego Casati VE6DPC

SCRIPT =	70_NOVNC.sh
NO_BUILD =	Yes

include ../common.mk
