COMMENT=	varanny is an enhancement tool for VARA, a widely used software modem in amateur radio digital transmissions.

DISTNAME=	varanny
V=		0.3.2
EXTRACT_SUFX=	.zip
DISTFILE=	varanny-linux-amd64.zip
SITES=		https://github.com/islandmagic/varanny/releases/download/0.3.2/varanny-linux-amd64.zip
MAINTAINER=	Diego Casati VE6DPC

SCRIPT=		110_VARANNY.sh

include ../common.mk
